---
services:
  freqtrade:
    build: .
    restart: unless-stopped
    volumes:
      - "/home/aperalta/apps/freqtrade/ft_userdata/user_data:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url postgresql+psycopg2://superadmin:f_QS2x.umnP5Uv%5B@brota-db-uk2dxl:5432/freqtrade
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
